language: python
python:
- '3.6'
script:
- pip install coverage
- pip install -U flake8 xmldiff
- pip install -r requirements.txt
- python setup.py install
- flake8 galaxyxml --ignore=E2,E3,E4,E5,W3,W505,C901,E501
- python examples/example.py > tmp.xml
- xmldiff tmp.xml examples/tool.xml
- nosetests --with-coverage --cover-package=galaxyxml
deploy:
  provider: pypi
  username: __token__
  on:
    tags: true
  distributions: sdist bdist_wheel
  edge: true
  skip_existing: true
